version: '3'

services:
  store-database:
    restart: always
    container_name: WebStore-Database
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: Store-Database
      MYSQL_ROOT_PASSWORD: 29426030
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=29426030--execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    expose:
    - "3306"

  webstore-system:
    depends_on:
    - store-database
    build: ./
    expose:
    - "8080"
    ports:
    - "8080:8080"
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    command: mvn clean spring-boot:run
    environment:
    - WAIT_HOSTS:mysql:3306
